Add swagger doc
SoftwareEngineeringDaily/sedaily-event-stream pull request #70
Opened 2018-04-04 23:46 UTC by abdulbasitkay

My attempt at #59, hope this works

2018-04-06 04:41 UTC, andrewmarklloyd commented
Looking good so far @abdulbasitkay! I started a review and I have a few notes here:
- We've disabled authentication for now, but I think it is a good idea to keep the documentation so nice work.
- I don't think we need the `server/docs/parameters.yaml` file since none of the endpoints support it. I assume this was a copy over from the other API project?
- I would add docs for the `server/routes/event.route.js` as well. That route doesn't have quite the same validation yet but after [issue 57](https://github.com/SoftwareEngineeringDaily/sedaily-devops/issues/57) it should

2018-04-08 11:25 UTC, abdulbasitkay commented
Thanks for the feedback @andrewmarklloyd,
I didn't get your last point. I've already added some docs to `server/routes/event.route.js` or were you referring to `server/routes/error.route.js` that's mentioned in issue #57?

2018-04-09 19:13 UTC, andrewmarklloyd commented
Sorry about that, you're right I meant `error.route.js`

2018-04-09 19:14 UTC, andrewmarklloyd commented
Let's merge this in and we can add a new issue to add docs for `error.route.js`

2018-04-09 19:25 UTC, andrewmarklloyd requested changes

2018-04-09 19:25 UTC, andrewmarklloyd commented on server/docs/definitions.yaml
> +        description: raw data of the event being streamed
The eventData maps to a specific eventType's required keys. For example the [`playEpisode` eventType](https://github.com/SoftwareEngineeringDaily/sedaily-devops/blob/develop/config/param-validation.js#L38) eventData has 3 fields: episodeName, minutesPlayed, and minutesRemaining. I would add an example, like:

```
example: {
    episodeName: "Ethereum Governance with Hudson Jameson",
    minutesPlayed: 1622.53,
    minutesRemaining: 117.62
}
```

2018-04-09 20:32 UTC, andrewmarklloyd approved these changes

2018-04-09 20:32 UTC, merged

2018-04-09 20:47 UTC, andrewmarklloyd commented
Created a new issue #73